### ISSUE TITLE
Update annotation scripts for NF processed datasets to automatically add license

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nfportalutils#106]
I think we should have default key:value 
`license: https://creativecommons.org/licenses/by/4.0/`. I am going back to add CC BY 4.0 license now. @allaway would that be OK?

<img width="825" alt="image" src="https://github.com/nf-osi/nfportalutils/assets/32753274/786d9f6e-bbc4-4f9f-92ee-6a125d49f22a">

**Comment by allaway** [comment]
Hmm, I think this is fine, but the default license for NF-OSI submitted data is CC0. Do we want to do the same? Should we inherit the upstream license?

**Comment by anngvu** [comment]
Let's do CC0 then.

**Comment by anngvu** [comment]
Actually, still questioning right license. I think we should actually confirm with NTAP the license to use for data from the NF-OSI Processing Initiative.

**Comment by allaway** [comment]
It would be reasonable to consult with them! Thanks!

**Comment by anngvu** [comment]
Actually, licensing is too complicated and I don't think this can be automated as things currently are. It should still be set during the final human review.
