### ISSUE TITLE
Create "Tools" or "Other Resources" folder based on new project template specs

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nfportalutils#149]
There has been some discussion about officially accommodating sharing of non-Raw Data resources (e.g. protocols, see also https://github.com/nf-osi/dcc-site/issues/660), so it makes sense to create a home for these (called "Tools", "Protocols", or "Other Resources"*). I've seen some contributors put protocols in "Raw Data", which make things a little confusing.

*Does anyone have a preference or other suggestion? @cconrad8 @allaway @jaybee84

**Comment by allaway** [comment]
Should we add a resourceType column to the DSP and create a folder for each
"resourceType" that is submitted in the DSP?

**Comment by anngvu** [comment]
Work on upstream https://github.com/nf-osi/dcc-site/issues/660 has been merged so we will schedule this for next sprint.
