### ISSUE TITLE
Provide Docker image for nfportalutils

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nfportalutils#23]
**Is your feature request related to a problem? Please describe.**
This image would be useful for automated jobs or just allow someone to run some of the functions easily and reproducibly.

**Describe the solution you'd like**
Solution example basically follows our colleagues at https://github.com/Sage-Bionetworks/cleanAD ("Tools for cleaning and organizing study data for the AD Knowledge Portal"), who provides the image https://hub.docker.com/r/sagebionetworks/cleanad.

**Describe alternatives you've considered**

**Additional context**
Should we request access to sagebionetworks dockerhub account or create separate nf-osi account for dockerhub?

**Comment by allaway** [comment]
We could ask for access to sagebionetworks, or we can use the nf-osi
dockerhub account (already exists, though we don't do much) - if you send
me your dockerhub username I'll add you!

**Comment by anngvu** [comment]
See https://github.com/nf-osi/nfportalutils/pkgs/container/nfportalutils. For better image labels, commits can be tagged.
