### ISSUE TITLE
Reassess annotation cols in default fileview

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nfportalutils#42]
Isn't the default (local) project fileview for the study project lead? Thus it should be most useful for helping the PL track and organize things. Yet default fileviews created for the project currently specify many columns that are not even in the annotation templates, or only in 1-2 specialized templates, such as `consortium`, `accessTeam`, `isXenograft`, `modelOf` -- not useful for many projects today. This configuration was probably based on certain projects (e.g. ones with consortia) but don't represent the many of the projects today. (Yes, I should have questioned these columns _even more_ at time of porting the old code.) 

The view configuration should be more minimal, and there should be instructions for how the project lead can add extra columns to their view that they may want. Basically, start with what a PL would actually facet on.

### Commonly Informative
These should be included by default.
- resourceType
- assay
- dataType
- dataSubtype
- diagnosis
- tumorType
- fileFormat
- individualID
- specimenID
- sex
- age (we don't include ageUnit because the lead knows what unit they used for measurement)
- nf1Genotype
- nf2Genotype
- species
- progressReportNumber
- modelSystemName
- experimentalCondition

### Unclear Information Value
- isCellLine
- isMultiSpecimen
- isMultiIndividual

### Low Information Value
These don't actually provide any real information that help with practical data/file management and should be hidden.
- fundingAgency:  Unless the data has multiple associations for this property (not the case nowadays), why display this? The project lead already knows what it is and is not going get anything from possible faceting on this.
- studyName: Same as above.
- studyId: Same as above.
- isXenograft: Should only be added if the study does involve transplantation.
- transplantationType: Same as above.
- compoundName: Should only be added if the study involves drug screens.
- modelOf: This is deprecated anyway.
- readPair: Should be something that is added back if applies/desired.
- accessType: Does any project use this anymore?
- accessTeam:  Same as above.
- consortium: Same as above.

**Comment by allaway** [comment]
>This configuration was probably based on certain projects (e.g. ones with consortia) but don't represent the many of the projects today.

I think that it's even worse than that - it's probably based on just one project and was propagated from there. I am not entirely sure why the original list was the way it was as these were configured by someone else, but it's definitely been a thing on my mental list to revisit at some point. 

I agree with your list - the 'commonly informative' ones are probably the ones that should be there at the outset. 
PIs can easily  pull in all of the project-relevant annotations/ additional columns after they annotate files by clicking "add all annotations" in the fileview schema config, so I think a more minimal schema to start makes sense.
