### ISSUE TITLE
Refactor old access annotation code from hackathon and add to this package

### ISSUE THREAD

**Issue by allaway** [nf-osi/nfportalutils#79]

**Comment by anngvu** [comment]
Implemented in https://github.com/nf-osi/nfportalutils/pull/78

**Comment by allaway** [comment]
Apologies for not adding any info to the original issue. The current PR is great! One additional thing that is needed for projectLive is to set, file-wise, the annotation for accessType to "PUBLIC" or "PRIVATE". 

Or, I think we previously chatted about possibly using the language of "RELEASED" vs "EMBARGOED," which is probably more accurate than PUBLIC for files where All Synapse Users can download, but are protected by an AR.

**Comment by anngvu** [comment]
Hmm, will keep open and address this as its own annotation function.
