### ISSUE TITLE
Add script to provide basic scoring of annotations

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nfportalutils#87]
This script is useful when reviewing metadata for a project at project closeout.
It will essentially be a re-validation of the data files, but also:
1. Attempts to summarize quality over all files in the repo, not just for a single manifest.
2. ~Gives extra credit for going beyond bare minimum.~ split to https://github.com/nf-osi/nfportalutils/issues/122

Update: Do the pass/fail for an entire project first, then work on 2.

**Comment by allaway** [comment]
Yessss! Big 👍
