### ISSUE TITLE
Bug report: annotation of nf-core-rnaseq output files fails

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nfportalutils#89]
Problem:
I am running the following command to annotate files in https://www.synapse.org/#!Synapse:syn51144753

```
> nfportalutils::syn_login()
Welcome, Jineta Banerjee!
> nfportalutils::map_sample_output_rnaseq("syn51144753")
> Going through the outputs...this may take some seconds.
>
```

Expected output:
Sample annotations to be added to .bam, .bai, .sf files in the `star_salmon` folder.

Observed output:
No updates of annotations

This is currently a blocker for data release.

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6.3

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nfportalutils_0.0.0.9110

loaded via a namespace (and not attached):
 [1] compiler_4.2.1    magrittr_2.0.3    Matrix_1.5-3      tools_4.2.1       withr_2.5.0       rstudioapi_0.14   Rcpp_1.0.10      
 [8] reticulate_1.27   grid_4.2.1        data.table_1.14.6 jsonlite_1.8.4    png_0.1-8         lattice_0.20-45  
> 
```

**Comment by allaway** [comment]
@jaybee84 , is it possible you were trying to run this during migration to the new synapse stack? Typically this is on sunday evenings (though in slack it looks like it might have been Saturday evening this week).

**Comment by jaybee84** [comment]
@allaway good point.. to test this I ran it again just now... no error message, but still no annotations :(

**Comment by allaway** [comment]
Looking closer at your code chunk, it looks like you are using a helper function, not the main function which includes the annotation step (map_sample_io), as in this vignette: https://github.com/nf-osi/nfportalutils/blob/develop/vignettes/annotate-nf-processed-data.Rmd

**Comment by jaybee84** [comment]
Aha! that was it. I was able to annotate the files with the current version of the functions. Thanks @allaway for pointing me to the vignettes. I was looking for an example application, but it looks like I didnt look carefully enough :)
